LOAD_MODEL_EPOCH: 0
DEBUG: true
N_EPOCHS: 100
LOAD_G_MODEL_SCORE: 0
LOAD_D_MODEL_SCORE: 0
MODEL_NO: 0
BATCH_SIZE: 32
N_SPLIT: 10
MAX_LR: 0.0002
MIN_LR: 0.000001
LAMBDA1: 75
LAMBDA2: 25
SEED: 1
DATALOADER_SEED: 1
DEVICE: cpu
SIZE: 352